'use strict';

(function(root,factory){
  const Occluders=root?.SteelMothWebGPUOccluders||((typeof module==='object'&&module.exports)?require('./webgpu_occluders.js'):null);
  const Lighting=root?.SteelMothWebGPULighting||((typeof module==='object'&&module.exports)?require('./webgpu_lighting.js'):null);
  const api=factory(Occluders,Lighting,root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.SteelMothWebGPUTileCulling=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(Occluders,Lighting,root){
  if(!Occluders)throw new Error('SteelMothWebGPUOccluders is required before webgpu_tile_culling');
  if(!Lighting)throw new Error('SteelMothWebGPULighting is required before webgpu_tile_culling');

  const SCHEMA='steelmoth-webgpu-tile-culling/v1';
  const SNAPSHOT_SCHEMA='steelmoth-webgpu-tile-culling-snapshot/v1';
  const TILE_RECORD_STRIDE=16;
  const FLAGS=Object.freeze({OCCLUDER:1,STATIC:2,DYNAMIC:4,TRANSPARENT:8,LIT:16,DSO_RELEVANT:32});
  const RESERVED_CONSUMERS=Object.freeze(['gtao','ssgi','volumetrics']);
  const DEFAULTS=Object.freeze({maxLightsPerTile:Lighting.MAX_LIGHTS,maxLightRefs:65536});
  const FALLBACK_BUFFER_USAGE=Object.freeze({MAP_READ:0x0001,COPY_SRC:0x0004,COPY_DST:0x0008,STORAGE:0x0080});
  const MAP_MODE_READ=0x0001;
  const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const usage=names=>names.reduce((v,n)=>v|Number(root?.GPUBufferUsage?.[n]??FALLBACK_BUFFER_USAGE[n]??0),0);
  const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  const hashBytes=bytes=>{let h=2166136261>>>0;for(const v of bytes){h^=v;h=Math.imul(h,16777619)>>>0}return h>>>0};

  function unwrapOccluders(input){const snap=input?.snapshot?.schema===Occluders.SNAPSHOT_SCHEMA?input.snapshot:input;if(!snap||snap.schema!==Occluders.SNAPSHOT_SCHEMA)throw new Error(`SM-504 requires ${Occluders.SNAPSHOT_SCHEMA} input from SM-300`);return snap}
  function sameGrid(a,b){return !!a&&!!b&&a.width===b.width&&a.height===b.height&&a.tileSize===b.tileSize&&a.columns===b.columns&&a.rows===b.rows&&a.count===b.count}
  function tilePixelArea(grid,index){const x=index%grid.columns,y=Math.floor(index/grid.columns),x0=x*grid.tileSize,y0=y*grid.tileSize,x1=Math.min(grid.width,x0+grid.tileSize),y1=Math.min(grid.height,y0+grid.tileSize);return Math.max(0,x1-x0)*Math.max(0,y1-y0)}
  function markBounds(flags,grid,bounds,flag){if(!Array.isArray(bounds)||bounds.length<4)return;const q=Occluders.tileRange(bounds,grid);for(let y=q.y0;y<=q.y1;y++)for(let x=q.x0;x<=q.x1;x++)flags[y*grid.columns+x]|=flag}
  function lightBounds(light){const p=light?.position||[light?.x,light?.y,light?.z],x=finite(p?.[0]),y=finite(p?.[1]),r=Math.max(0,finite(light?.radius));return[x-r,y-r,x+r,y+r]}
  function validateLightIdentity(snapshot,lights){const ids=(lights||[]).map(l=>String(l?.id||''));if(ids.length!==snapshot.lightIds.length||ids.some((id,i)=>id!==snapshot.lightIds[i]))throw new Error('SM-504 light identity/order mismatch: rebuild shared tile metadata from the canonical SM-204 light list')}

  function buildSharedTileSnapshot(occluderInput,lights=[],options={}){
    const occluders=unwrapOccluders(occluderInput),grid=occluders.grid,d={...DEFAULTS,...options},canonical=(lights||[]).slice(0,Lighting.MAX_LIGHTS),flags=new Uint32Array(grid.count),occluderCounts=new Uint32Array(grid.count),lists=Array.from({length:grid.count},()=>[]),overflow=new Uint8Array(grid.count);
    for(let i=0;i<grid.count;i++){const count=Number(occluders.tileHeaders?.[i*2+1]||0);occluderCounts[i]=count;if(count)flags[i]|=FLAGS.OCCLUDER}
    for(const rec of occluders.records||[]){const flag=String(rec.updateClass||'static')==='dynamic'?FLAGS.DYNAMIC:FLAGS.STATIC;markBounds(flags,grid,rec.bounds,flag)}
    for(const b of options.transparentBounds||[])markBounds(flags,grid,b,FLAGS.TRANSPARENT);
    let droppedLightRefs=0;
    canonical.forEach((light,index)=>{const q=Occluders.tileRange(lightBounds(light),grid);for(let y=q.y0;y<=q.y1;y++)for(let x=q.x0;x<=q.x1;x++){const ti=y*grid.columns+x,l=lists[ti];if(l.includes(index))continue;if(l.length>=d.maxLightsPerTile){overflow[ti]=1;droppedLightRefs++;continue}l.push(index);flags[ti]|=FLAGS.LIT}});
    const tileRecords=new Uint32Array(Math.max(4,grid.count*4)),refs=[];for(let i=0;i<grid.count;i++){tileRecords[i*4]=flags[i];tileRecords[i*4+1]=occluderCounts[i];tileRecords[i*4+2]=refs.length;const room=Math.max(0,d.maxLightRefs-refs.length),count=Math.min(lists[i].length,room);tileRecords[i*4+3]=count;for(let j=0;j<count;j++)refs.push(lists[i][j]);if(count<lists[i].length){overflow[i]=1;droppedLightRefs+=lists[i].length-count}}
    const lightRefs=Uint32Array.from(refs.length?refs:[0]);let submittedPixelLightTests=0,litTiles=0,occupiedTiles=0,dynamicTiles=0,transparentTiles=0,maxLights=0;for(let i=0;i<grid.count;i++){const lc=tileRecords[i*4+3];submittedPixelLightTests+=tilePixelArea(grid,i)*lc;if(lc)litTiles++;if(flags[i]&FLAGS.OCCLUDER)occupiedTiles++;if(flags[i]&FLAGS.DYNAMIC)dynamicTiles++;if(flags[i]&FLAGS.TRANSPARENT)transparentTiles++;maxLights=Math.max(maxLights,lc)}const baselinePixelLightTests=grid.width*grid.height*canonical.length,avoidedPixelLightTests=Math.max(0,baselinePixelLightTests-submittedPixelLightTests),workReduction=baselinePixelLightTests?avoidedPixelLightTests/baselinePixelLightTests:0;
    const sigBytes=new Uint8Array(tileRecords.byteLength+lightRefs.byteLength),a=new Uint8Array(tileRecords.buffer,tileRecords.byteOffset,tileRecords.byteLength),b=new Uint8Array(lightRefs.buffer,lightRefs.byteOffset,lightRefs.byteLength);sigBytes.set(a,0);sigBytes.set(b,a.length);const signature=hashBytes(sigBytes);
    return{schema:SNAPSHOT_SCHEMA,roomId:String(occluders.roomId||''),sourceOccluderSchema:occluders.schema,grid:{...grid},flags,tileRecords,lightRefs,lightIds:canonical.map(l=>String(l?.id||'')),lightOverflow:overflow,signature,diagnostics:{tileCount:grid.count,occupiedTiles,dynamicTiles,transparentTiles,litTiles,unlitTiles:grid.count-litTiles,lightCount:canonical.length,lightRefCount:refs.length,droppedLightRefs,overflowTileCount:Array.from(overflow).filter(Boolean).length,maxLightsPerTile:maxLights,baselinePixelLightTests,submittedPixelLightTests,avoidedPixelLightTests,workReduction,reservedConsumers:[...RESERVED_CONSUMERS],singleTileAuthority:'SM-300 grid reused verbatim'}}
  }

  function tileIndexAt(snapshot,x,y){const g=snapshot?.grid;if(!g||g.count<=0)return-1;const tx=clamp(Math.floor(finite(x)/g.tileSize),0,g.columns-1),ty=clamp(Math.floor(finite(y)/g.tileSize),0,g.rows-1);return ty*g.columns+tx}
  function lightIndicesForTile(snapshot,index){if(snapshot?.schema!==SNAPSHOT_SCHEMA)throw new Error(`SM-504 requires ${SNAPSHOT_SCHEMA}`);if(index<0||index>=snapshot.grid.count)return[];const off=snapshot.tileRecords[index*4+2]||0,count=snapshot.tileRecords[index*4+3]||0,out=[];for(let i=0;i<count;i++)out.push(snapshot.lightRefs[off+i]>>>0);return out}
  function lightsForPoint(snapshot,lights,x,y){validateLightIdentity(snapshot,lights);const index=tileIndexAt(snapshot,x,y);return lightIndicesForTile(snapshot,index).map(i=>lights[i]).filter(Boolean)}
  function shadePixelReferenceCulled(sample,lights,snapshot,settings={},screenXY=[0,0],debug='final'){const local=lightsForPoint(snapshot,lights,screenXY[0],screenXY[1]);if(debug==='tile-light-count'){const v=clamp(local.length/Lighting.MAX_LIGHTS,0,1);return[v,v,v,1]}return Lighting.shadePixelReference(sample,local,settings,screenXY,debug)}

  function withDSORelevance(snapshot,plan){if(snapshot?.schema!==SNAPSHOT_SCHEMA)throw new Error(`SM-504 requires ${SNAPSHOT_SCHEMA}`);if(!plan?.grid||!sameGrid(snapshot.grid,plan.grid))throw new Error('SM-504 DSO plan grid must be identical to the shared SM-300 tile grid');if(plan.roomId!=null&&snapshot.roomId&&String(plan.roomId)!==String(snapshot.roomId))throw new Error(`SM-504 DSO room mismatch: tiles=${snapshot.roomId} dso=${plan.roomId}`);const flags=new Uint32Array(snapshot.flags),tileRecords=new Uint32Array(snapshot.tileRecords);let relevant=0;for(let i=0;i<snapshot.grid.count;i++){const count=Number(plan.tileHeaders?.[i*2+1]||0);if(count){flags[i]|=FLAGS.DSO_RELEVANT;tileRecords[i*4]|=FLAGS.DSO_RELEVANT;relevant++}else{flags[i]&=~FLAGS.DSO_RELEVANT;tileRecords[i*4]&=~FLAGS.DSO_RELEVANT}}return{...snapshot,flags,tileRecords,dsoSourceSignature:Number(plan.signature||0)>>>0,diagnostics:{...snapshot.diagnostics,dsoRelevantTiles:relevant}}}
  function buildDSOWork(plan,snapshot,workgroupSize=8){if(snapshot?.schema!==SNAPSHOT_SCHEMA)throw new Error(`SM-504 requires ${SNAPSHOT_SCHEMA}`);if(!plan?.grid||!sameGrid(snapshot.grid,plan.grid))throw new Error('SM-504 DSO work cannot diverge from shared tile authority');const active=[];for(let i=0;i<snapshot.grid.count;i++){const flag=(snapshot.tileRecords[i*4]||0)&FLAGS.DSO_RELEVANT,count=Number(plan.tileHeaders?.[i*2+1]||0);if(!!flag!==!!count)throw new Error(`SM-504 DSO relevance drift at tile ${i}`);if(flag)active.push(i)}const g=snapshot.grid,groupsPerTileAxis=Math.ceil(g.tileSize/workgroupSize),groupsPerTile=groupsPerTileAxis*groupsPerTileAxis,fullScreenWorkgroups=Math.ceil(g.width/workgroupSize)*Math.ceil(g.height/workgroupSize),submittedWorkgroups=active.length*groupsPerTile,avoidedWorkgroups=Math.max(0,fullScreenWorkgroups-submittedWorkgroups);return{schema:'steelmoth-webgpu-tile-dso-work/v1',roomId:snapshot.roomId,grid:{...g},activeTiles:Uint32Array.from(active.length?active:[0]),activeTileCount:active.length,workgroupSize,groupsPerTile,fullScreenWorkgroups,submittedWorkgroups,avoidedWorkgroups,workReduction:fullScreenWorkgroups?avoidedWorkgroups/fullScreenWorkgroups:0,exactCoverage:true}}

  function debugTileOverlay(snapshot){if(snapshot?.schema!==SNAPSHOT_SCHEMA)return[];const g=snapshot.grid,out=[];for(let i=0;i<g.count;i++){const f=snapshot.tileRecords[i*4]||0,lc=snapshot.tileRecords[i*4+3]||0;if(!f&&!lc)continue;const x=i%g.columns,y=Math.floor(i/g.columns);out.push({tile:i,rect:[x*g.tileSize,y*g.tileSize,Math.min(g.width,(x+1)*g.tileSize),Math.min(g.height,(y+1)*g.tileSize)],flags:f,occluders:snapshot.tileRecords[i*4+1]||0,lights:lc,dsoRelevant:!!(f&FLAGS.DSO_RELEVANT)})}return out}

  class WebGPUSharedTileBuffers{
    constructor(options={}){if(!options.device)throw new Error('WebGPUSharedTileBuffers requires GPUDevice');this.device=options.device;this.queue=options.queue||options.device.queue;this.labelPrefix=String(options.labelPrefix||'SteelMothSM504');this.tileBuffer=null;this.lightRefBuffer=null;this.tileCapacity=0;this.lightRefCapacity=0;this.snapshot=null;this.uploadCount=0}
    _ensure(snapshot){const tileBytes=Math.max(TILE_RECORD_STRIDE,snapshot.tileRecords.byteLength),refBytes=Math.max(4,snapshot.lightRefs.byteLength);if(!this.tileBuffer||this.tileCapacity<tileBytes){this.tileBuffer?.destroy?.();this.tileCapacity=Math.max(tileBytes,this.tileCapacity*2||TILE_RECORD_STRIDE);this.tileBuffer=this.device.createBuffer({label:`${this.labelPrefix}:tile-records`,size:this.tileCapacity,usage:usage(['STORAGE','COPY_DST','COPY_SRC'])})}if(!this.lightRefBuffer||this.lightRefCapacity<refBytes){this.lightRefBuffer?.destroy?.();this.lightRefCapacity=Math.max(refBytes,this.lightRefCapacity*2||4);this.lightRefBuffer=this.device.createBuffer({label:`${this.labelPrefix}:light-refs`,size:this.lightRefCapacity,usage:usage(['STORAGE','COPY_DST','COPY_SRC'])})}}
    update(snapshot){if(snapshot?.schema!==SNAPSHOT_SCHEMA)throw new Error(`SM-504 GPU buffers require ${SNAPSHOT_SCHEMA}`);if(snapshot.diagnostics?.droppedLightRefs)throw new Error('SM-504 refuses truncated light lists; increase bounded light-ref capacity');this._ensure(snapshot);this.queue.writeBuffer(this.tileBuffer,0,snapshot.tileRecords);this.queue.writeBuffer(this.lightRefBuffer,0,snapshot.lightRefs);this.snapshot=snapshot;this.uploadCount++;return this.bindings()}
    bindings(){if(!this.snapshot||!this.tileBuffer||!this.lightRefBuffer)throw new Error('SM-504 tile buffers are not initialized');return{schema:SCHEMA,tileRecords:this.tileBuffer,lightRefs:this.lightRefBuffer,tileCount:this.snapshot.grid.count,lightRefCount:this.snapshot.diagnostics.lightRefCount,tileSize:this.snapshot.grid.tileSize,columns:this.snapshot.grid.columns,signature:this.snapshot.signature}}
    async readback(){const b=this.bindings(),tileBytes=this.snapshot.tileRecords.byteLength,refBytes=Math.max(4,this.snapshot.lightRefs.byteLength),readTile=this.device.createBuffer({label:`${this.labelPrefix}:tile-readback`,size:Math.max(4,tileBytes),usage:usage(['COPY_DST','MAP_READ'])}),readRefs=this.device.createBuffer({label:`${this.labelPrefix}:ref-readback`,size:refBytes,usage:usage(['COPY_DST','MAP_READ'])}),encoder=this.device.createCommandEncoder({label:`${this.labelPrefix}:readback`});encoder.copyBufferToBuffer(b.tileRecords,0,readTile,0,tileBytes);encoder.copyBufferToBuffer(b.lightRefs,0,readRefs,0,refBytes);this.queue.submit([encoder.finish()]);await Promise.all([readTile.mapAsync(Number(root?.GPUMapMode?.READ??MAP_MODE_READ)),readRefs.mapAsync(Number(root?.GPUMapMode?.READ??MAP_MODE_READ))]);const tileRecords=new Uint32Array(readTile.getMappedRange().slice(0,tileBytes)),lightRefs=new Uint32Array(readRefs.getMappedRange().slice(0,refBytes));readTile.unmap();readRefs.unmap();readTile.destroy();readRefs.destroy();return{tileRecords,lightRefs:lightRefs.slice(0,Math.max(1,this.snapshot.lightRefs.length))}}
    diagnostics(){return{schema:SCHEMA,valid:!!this.snapshot,uploadCount:this.uploadCount,tileCapacity:this.tileCapacity,lightRefCapacity:this.lightRefCapacity,snapshot:this.snapshot?clone(this.snapshot.diagnostics):null,reservedConsumers:[...RESERVED_CONSUMERS],debugOverlay:this.snapshot?debugTileOverlay(this.snapshot):[]}}
    close(){this.tileBuffer?.destroy?.();this.lightRefBuffer?.destroy?.();this.tileBuffer=null;this.lightRefBuffer=null;this.snapshot=null;this.tileCapacity=0;this.lightRefCapacity=0}
  }

  return{SCHEMA,SNAPSHOT_SCHEMA,TILE_RECORD_STRIDE,FLAGS,RESERVED_CONSUMERS,DEFAULTS,sameGrid,tilePixelArea,buildSharedTileSnapshot,tileIndexAt,lightIndicesForTile,lightsForPoint,shadePixelReferenceCulled,withDSORelevance,buildDSOWork,debugTileOverlay,WebGPUSharedTileBuffers};
});
