'use strict';
// Execute the comparison's source guards/accounting helpers with controlled APIs.
// No shader, browser, or GPU execution is claimed.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/\r\n/g,'\n'),page=read('webgpu-gtao-adoption-comparison.html'),canonical=read('webgpu-target-benchmark.html');
const hash=text=>crypto.createHash('sha256').update(text).digest('hex'),blob=text=>crypto.createHash('sha1').update(`blob ${Buffer.byteLength(text)}\0`).update(text).digest('hex');
assert.equal(blob(read('tools/experiments/frozen_sm601_readback.js')),'f4f82852d3bf04b5c9c665f5370f1a7f915325ff');
assert.equal(blob(read('tools/experiments/frozen_sm601_counter.js')),'af765d115a0b8f02684c4d7a68d5549ba100a2e4');
function scene(text){const start=text.indexOf('    function buildScene('),end=text.indexOf('\n    let scene=',start);assert(start>=0&&end>start);return text.slice(start,end)}
assert.equal(scene(page),scene(canonical),'canonical moving fixture must remain exact');
const G=require('../engine/webgpu_gtao.js'),GT=require('../engine/webgpu_gtao_stabilization.js');globalThis.SteelMothWebGPUGTAOStabilization=GT;
const Readback=require('./experiments/frozen_sm601_readback.js'),Counter=require('./experiments/frozen_sm601_counter.js');
assert(Readback.WebGPUGTAOTemporal.prototype instanceof GT.WebGPUGTAOTemporal,'frozen adapter must reuse production temporal base');
assert.equal(hash(G.RAW_WGSL),'d6bbbf28517866d9b3ca6e5de3b54847e4147f89a15df1be3ce47200d0cbae78');assert.equal(hash(G.UPSAMPLE_WGSL),'7ddda64b8e31f11998ce77abb721c4b1e105e468e1e3785e28374eb0c9ef81cd');assert.equal(hash(GT.TEMPORAL_WGSL),Counter.BASELINE_SHA256);
assert(!/device\.queue\.[\w]+\s*=/.test(page)&&!page.includes('new Proxy(device.queue'),'native GPUQueue must not be patched');
function helper(start,end){const i=page.indexOf(start),j=page.indexOf(end,i);assert(i>=0&&j>i);return page.slice(i,j)}
let clock=10;const variants=[{id:'baseline-blocking',counter:false,deferred:false},{id:'counter-blocking',counter:true,deferred:false},{id:'baseline-deferred',counter:false,deferred:true},{id:'counter-deferred',counter:true,deferred:true}],calls=[],nativeQueue=Object.freeze({writeBuffer(...args){calls.push(['write',args])},submit(buffers){calls.push(['submit',buffers]);return'native'},onSubmittedWorkDone(){return Promise.resolve('done')}});
const context={VARIANTS:variants,runOffset:0,active:null,now:()=>++clock,check:(c,m)=>assert(c,m),device:{queue:nativeQueue},GT,directQueries:{},passIndices:{'SteelMothGTAO:half-horizon':0,'SteelMothGTAO:depth-aware-upsample':2,'SteelMothGTAOStabilization:temporal':4,'SteelMothGTAOReadback:temporal':4},Uint32Array,Uint8Array,Array,Set};vm.createContext(context);
vm.runInContext(helper('  function rotation(', '  const loadBitmap='),context);
vm.runInContext(helper('    function producerQueue(', '    directQueries='),context);
vm.runInContext(helper('    function timedDevice(', '    raw=new'),context);
function record(variant){return{variant:variant.id,encodingStart:{},encodingCpuMs:{},submitApiCpuMs:{},submissions:[],diagnosticMapLatencyCpuMs:[],seen:new Set(),statsCopySeen:false,inCallback:true,scope:{submit(buffers,metadata){calls.push(['scope',buffers,metadata]);return'scoped'},recordHostWait(name,ms){calls.push(['host-wait',name,ms])},async measureHostWait(name,callback){calls.push(['host-wait-api',name]);return callback()}}}}
(async()=>{
  context.candidate=await Counter.createCandidate(GT.TEMPORAL_WGSL);assert.equal(context.candidate.candidateSha256,'11024a2f13f20abda1dee7cdc1a6d6703ecfc1982929ed51ccaa7b071579acf7');await assert.rejects(Counter.createCandidate(GT.TEMPORAL_WGSL+'\n'),/identity/);
  for(let offset=0;offset<3;offset++){context.runOffset=offset;const counts=new Map(variants.map(v=>[v.id,[0,0,0,0]]));for(let frame=0;frame<600;frame++){const order=context.rotation(frame);assert.equal(new Set(order.map(v=>v.id)).size,4);order.forEach((variant,index)=>counts.get(variant.id)[index]++)}for(const positions of counts.values())assert.deepEqual(positions,[150,150,150,150])}
  for(const size of [4,8,16,33]){const left=new Uint8Array(size),right=left.slice();assert(context.equalBytes(left,right));for(const index of [0,Math.floor(size/2),size-1]){right[index]^=1;assert(!context.equalBytes(left,right));right[index]^=1}assert(!context.equalBytes(left,new Uint8Array(size+1)))}
  const words=[80,20,5,5,5,5,0,0];context.validateWords(words,100);assert.throws(()=>context.validateWords([80,20,5,5,5,5,1,0],100),/counter totals/);assert.throws(()=>context.validateWords([81,20,5,5,5,5,0,0],100),/counter totals/);
  const rawQueue=context.producerQueue('rawAndUpscale'),temporalQueue=context.producerQueue('temporal',variants[0].id),r=record(variants[0]);context.active=r;
  rawQueue.writeBuffer('raw',0,new Uint8Array(64));assert.equal(rawQueue.submit(['raw+upscale']),'scoped');
  const encoded=[];context.device.createCommandEncoder=()=>({beginComputePass(descriptor){encoded.push(descriptor);return{end(){}}},copyBufferToBuffer(...args){encoded.push(args)},finish(){return{}}});context.device.createShaderModule=descriptor=>descriptor;context.device.createBuffer=()=>{throw new Error('not needed')};
  const proxy=context.timedDevice(variants[0]),encoder=proxy.createCommandEncoder({label:'SteelMothGTAOStabilization:encoder'});encoder.beginComputePass({label:'SteelMothGTAOStabilization:temporal'}).end();encoder.copyBufferToBuffer({},0,{},0,32);assert.equal(r.statsCopySeen,true,'encoder must mutate the same retained row');assert(r.seen.has(4));temporalQueue.writeBuffer('params',0,new Uint8Array(32));assert.equal(temporalQueue.submit(['temporal+copy']),'scoped');assert.deepEqual(r.submissions,['rawAndUpscale','temporal']);assert.equal(calls.filter(call=>call[0]==='submit').length,0);assert.equal(calls.filter(call=>call[0]==='scope').at(-1)[2].diagnosticCopyBytes,32);
  context.active=record(variants[1]);assert.throws(()=>temporalQueue.submit(['wrong-variant']),/Cross-variant/);context.active=null;assert.equal(rawQueue.submit(['warmup']),'native');
  assert.equal(context.timedDevice(variants[1]).createShaderModule({label:'SteelMothGTAOStabilization:wgsl',code:GT.TEMPORAL_WGSL}).code,context.candidate.code);assert.equal(context.timedDevice(variants[1]).createShaderModule({label:'raw',code:G.RAW_WGSL}).code,G.RAW_WGSL);assert.throws(()=>context.timedDevice(variants[1]).createShaderModule({label:'SteelMothGTAOStabilization:wgsl',code:'drift'}),/Unexpected temporal shader/);
  async function mapCase(variant,deferCompletion){let release,mapped=false,rangeCalls=0;const data=new Uint32Array(words).buffer,b={mapAsync(){return new Promise(resolve=>{release=()=>{mapped=true;resolve()}})},getMappedRange(){assert(mapped);rangeCalls++;return data},unmap(){mapped=false}},row=record(variant);context.active=row;context.observeMap(b,variant);const promise=b.mapAsync(1);if(deferCompletion){row.inCallback=false;row.scope.recordHostWait=()=>{throw new Error('escaped scope')};context.active=null}release();await promise;const value=b.getMappedRange(0,32);assert.equal(value,data);assert.equal(rangeCalls,1,'observer must reuse existing native mapped range without a second overlapping request');assert.deepEqual(Array.from(row.rawStatsWords),words);assert.equal(row.diagnosticMapLatencyCpuMs.length,1);b.unmap();context.active=null}
  await mapCase(variants[0],false);await mapCase(variants[2],true);await mapCase(variants[3],true);
  console.log(JSON.stringify({ok:true,gpuExecution:false,checks:['exact frozen module blobs','canonical fixture and shader identity','600-frame/process-offset rotation balance','byte-exact output mutation rejection','eight-word counter invariants','two explicit submissions with same-row copy coverage','cross-variant submission refusal','guarded shader substitution','deferred completion avoids escaped host-wait scope','single native mapped-range observation']}));
})().catch(error=>{console.error(error?.stack||error);process.exitCode=1});
