'use strict';
const assert=require('assert');
const P=require('./sm800_precision_probe.js');
const r=P.deterministicReport();
assert.strictEqual(r.schema,'steelmoth-sm800-precision-study/v1');
assert.deepStrictEqual(r.coreInvariant,{g0:'rgba8unorm',objectId:'r32uint',depth:'depth32float'});
assert.strictEqual(r.layouts.length,5);
const by=Object.fromEntries(r.layouts.map(x=>[x.layout,x]));
assert.strictEqual(by.baseline.bytesPerPixel,36);
assert.strictEqual(by.material8.bytesPerPixel,32);
assert.strictEqual(by.octMaterial8.bytesPerPixel,28);
assert.strictEqual(by.hdr11.bytesPerPixel,32);
assert.strictEqual(by.combined.bytesPerPixel,24);
assert.strictEqual(by.combined.bytesSaved1080p,12*1920*1080);
assert.ok(r.oct8.pass,`oct8 max angular error ${r.oct8.maxAngleDeg}`);
assert.ok(r.oct8.maxAngleDeg<1.0);
assert.ok(r.material8.pass,`material8 max error ${r.material8.maxAbsError}`);
assert.ok(r.material8.maxAbsError<=1/510+1e-9);
console.log(`SM-800 deterministic PASS baseline=${by.baseline.mib1080p.toFixed(2)}MiB combined=${by.combined.mib1080p.toFixed(2)}MiB octMax=${r.oct8.maxAngleDeg.toFixed(4)}deg materialMax=${r.material8.maxAbsError.toFixed(6)}`);
