#!/usr/bin/env node
'use strict';
const assert=require('assert');
const G=require('../engine/webgpu_gbuffer.js');
const L=require('../engine/webgpu_lighting.js');
const P=require('../engine/webgpu_post.js');
const near=(a,b,e=1e-6,m='')=>assert.ok(Math.abs(a-b)<=e,`${m}: ${a} vs ${b}`);
const round=(v,n=7)=>Number(v.toFixed(n));
const checks=[];const check=(v,m)=>{assert.ok(v,m);checks.push(m)};
near(G.srgbChannelToLinear(.5),.2140411405,1e-9,'sRGB 0.5 decode');
near(P.linearChannelToSrgb(.18),.4613561295,1e-9,'18% linear grey display encode');
near(G.srgbChannelToLinear(P.linearChannelToSrgb(.18)),.18,1e-9,'18% grey round trip');
for(const v of [0,.0031308,.018,.18,.5,1])near(G.srgbChannelToLinear(P.linearChannelToSrgb(v)),v,2e-7,`round trip ${v}`);
for(const p of [[1,0,0],[0,1,0],[0,0,1],[1,1,1]])assert.deepStrictEqual(G.srgbToLinear(p),p,'primaries/white invariant at endpoints');
const tint=G.buildSceneInstances({materials:[{id:'m',overrides:{mode:'normal'}}],sprites:[{id:'s',category:'dynamic',atlas:'hd',spriteId:'x',materialId:'m',root:{y:0},transform:{x:0,y:0,w:1,h:1},style:{tint:[.5,.25,1],alpha:1,glow:false}}]},{source_size:[1,1],world_scale:1,regions:{x:[0,0,1,1]}})[0].tint;
near(tint[0],.2140411405,1e-9,'authored tint red decoded');near(tint[1],.0508760882,1e-9,'authored tint green decoded');
const lights=L.buildCanonicalLights({lights:[{id:'l',x:0,y:0,z:1,radius:10,intensity:1,color:[.5,.25,1]}]},{lighting:true,lightRadius:1,emissive:1});
near(lights[0].color[0],.2140411405,1e-9,'canonical light red decoded');near(lights[0].color[1],.0508760882,1e-9,'canonical light green decoded');
const dielectric={albedo:G.srgbToLinear([.5,.5,.5]),normalRoughness:[.5,.5,1,.5],heightMaterial:[0,0,1,0]};
const metal={...dielectric,heightMaterial:[0,1,1,0]};
const white=L.buildCanonicalLights({lights:[{id:'w',x:0,y:-20,z:10,radius:100,intensity:1,color:[1,1,1]}]},{lighting:true,lightRadius:1,emissive:1});
const settings={lighting:true,ambient:.18,normalStrength:1,heightStrength:1,roughnessScale:1,metalnessScale:1,materialAOStrength:1,pbrSpecularStrength:1};
const d=L.shadePixelReference(dielectric,white,settings,[0,0],'final'),m=L.shadePixelReference(metal,white,settings,[0,0],'final');
check(d.every(Number.isFinite)&&m.every(Number.isFinite),'dielectric/metal GGX references finite in linear HDR');
check(d.some(v=>v>0)&&m.some(v=>v>0),'dielectric/metal fixtures produce nonzero linear response');
const greyDisplay=P.linearToSrgb([.18,.18,.18]);near(greyDisplay[0],.4613561295,1e-9,'18% grey expected display value');
const post=P.applyPostReference([.18,.18,.18],[0,0,0],{bloom:false,saturation:1,gradeMix:0,vignette:0,grain:0,exposure:1,brightness:0,contrast:1,gamma:1,gradeTemperature:0,gradeTint:0,shadowLift:0,highlightGain:0});
check(post.every(Number.isFinite),'post reference returns finite display-encoded values');
check(G.MATERIAL_WGSL.includes('textureSample(albedoTex')&&!G.MATERIAL_WGSL.includes('pow(max(t.rgb,vec3f(0)),vec3f(2.4))'),'material WGSL consumes already-decoded linear albedo without hidden gamma math');
check(L.DEFERRED_WGSL.includes('D_GGX')&&L.DEFERRED_WGSL.includes('al.rgb')&&!L.DEFERRED_WGSL.includes('pow(al.rgb'),'GGX/direct-light WGSL consumes linear G0 without gamma-space conversion');
check(P.POST_WGSL.includes('linear_to_srgb')&&P.RAW_WGSL.includes('1.0/2.4'),'final/raw display paths explicitly encode sRGB');
console.log(JSON.stringify({ok:true,checks:checks.length,srgbHalf:round(G.srgbChannelToLinear(.5)),linear18Display:round(P.linearChannelToSrgb(.18)),dielectric:d.map(x=>round(x)),metal:m.map(x=>round(x))},null,2));
