'use strict';

// Deterministic policy and mocked API/lifetime evidence only; no shaders execute.
const assert=require('node:assert/strict');
const Forward=require('../engine/webgpu_forward_lighting.js');
const Water=require('../engine/webgpu_water.js');
const Foliage=require('../engine/webgpu_foliage.js');
const Ownership=require('../engine/webgpu_ownership.js');
const PseudoDepth=require('../engine/pseudo_depth.js');
const Lighting=require('../engine/webgpu_lighting.js');
const Hierarchy=require('../engine/webgpu_depth_hierarchy.js');
const Visibility=require('../engine/webgpu_visibility.js');
const SSGI=require('../engine/webgpu_ssgi.js');
const checks=[];
function check(name,fn){fn();checks.push(name);}
function deferred(){let resolve;const promise=new Promise(r=>{resolve=r;});return{promise,resolve};}
async function until(predicate){for(let i=0;i<64;i++){if(predicate())return;await Promise.resolve();}throw new Error('mock did not reach pending operation');}
function mockDevice(){
  const loss=deferred(),state={textures:[],buffers:[],groups:[],pipelines:[],commands:[],submits:[],waits:0,compileCalls:0,compileGate:null,completion:null,failSubmit:false};
  const device={lost:loss.promise,pushErrorScope(){},async popErrorScope(){return null;},createTexture(descriptor){const t={device,descriptor,destroyed:false,createView(){return{device,texture:t};},destroy(){t.destroyed=true;}};state.textures.push(t);return t;},createBuffer(descriptor){const b={device,descriptor,data:new Uint8Array(descriptor.size),destroyed:false,destroy(){b.destroyed=true;},mapAsync(){throw new Error('producer must not map diagnostics');}};state.buffers.push(b);return b;},createShaderModule(descriptor){return{device,descriptor,async getCompilationInfo(){state.compileCalls++;const gate=state.compileGate;state.compileGate=null;if(gate)await gate.promise;return{messages:[]};}};},createRenderPipeline(d){return pipeline(d);},createComputePipeline(d){return pipeline(d);},createBindGroup(descriptor){assert.equal(descriptor.layout.device,device);for(const e of descriptor.entries)assert.equal((e.resource.buffer||e.resource).device,device);const g={device,descriptor};state.groups.push(g);return g;},createCommandEncoder(){const c={device,passes:[]};function pass(descriptor){const r={descriptor,binds:[]};c.passes.push(r);return{setPipeline(p){assert.equal(p.device,device);r.pipeline=p;},setBindGroup(i,g){r.binds[i]=g;},draw(){},dispatchWorkgroups(){},end(){}};}return{beginRenderPass:pass,beginComputePass:pass,finish(){state.commands.push(c);return c;}};}};
  function pipeline(descriptor){const p={device,descriptor,getBindGroupLayout(i){return{device,pipeline:p,index:i};}};state.pipelines.push(p);return p;}
  device.queue={writeTexture(){},writeBuffer(b,offset,data){assert.equal(b.device,device);assert.equal(b.destroyed,false);b.data.set(new Uint8Array(data.buffer,data.byteOffset,data.byteLength),offset);},submit(commands){if(state.failSubmit)throw new Error('injected submit failure');state.submits.push(commands);},async onSubmittedWorkDone(){state.waits++;if(state.completion)await state.completion.promise;}};
  return{device,state,loss};
}
function canonical(device,width=20,height=16){
  const view=label=>({device,label}),base=()=>({device,width,height,valid:true,generation:1,updateCount:1,invalidationCount:0}),g={depth:view('depth'),g1:view('G1'),objectId:view('object')};
  const gbuffer={...base(),registry:{generation:1,resizeCount:0},_views(){return g;}},lightBuffer={device,label:'sm204:lights'},sceneView=view('opaque');
  const lighting={...base(),activeLightCount:1,registry:{generation:1,require(name){assert.equal(name,Lighting.LIGHT_BUFFER_NAME);return{handle:lightBuffer};}}},hierarchy={...base(),levelView(){return view('range');}},visibilityView=view('visibility'),visibility={...base(),bindings(){return{visibility:visibilityView};}};
  const a=view('incident A'),b=view('incident B'),ssgi={...base(),current:a,bindings(){return{indirectQuarter:this.current,quarterWidth:Math.ceil(width/4),quarterHeight:Math.ceil(height/4)};}};
  const paths={lighting,gbuffer,hierarchy,visibility,ssgi,opaqueResolvedView:sceneView};
  return{paths,source:Forward.sourceFromPaths(paths),ssgi,visibility,gbuffer,hierarchy,lighting,a,b};
}
function water(device){const w=new Water.WebGPUWaterPass({device,width:20,height:16});w.setField({width:2,height:2,rgba:new Uint8Array(16).fill(255),roomId:'room',revision:1});return w;}
function actualCanonical(device){
  // Real producer classes and registries on a mock device: lifetime tests only.
  // No build/render/update is run; valid flags stand in for previously completed work.
  const options={device,width:20,height:16},gbuffer=new Ownership.WebGPUOwnershipGBuffer(options),lighting=new Lighting.WebGPUDeferredLighting(options),hierarchy=new Hierarchy.WebGPUDepthHierarchy(options),visibility=new Visibility.WebGPUVisibilityComposition(options),ssgi=new SSGI.WebGPUSSGI(options);
  hierarchy.valid=visibility.valid=ssgi.valid=true;
  const paths={gbuffer,lighting,hierarchy,visibility,ssgi,opaqueResolvedView:ssgi.bindings().composed};
  return{paths,source:Forward.sourceFromPaths(paths),close(){gbuffer.close();lighting.close();hierarchy.close();visibility.close();ssgi.close();}};
}
const WATER_SETTINGS={advancedLighting:true,waterQuality:2,surface:{worldZ:0,category:'ground'}};

async function main(){
  check('optional settings off and bounded',()=>{assert.equal(Forward.DEFAULTS.advancedLighting,false);assert.equal(Forward.normalizeOptions({indirectWeight:99,energyMax:99}).indirectWeight,1);assert.equal(Forward.normalizeOptions({energyMax:99}).energyMax,.08);assert.deepEqual(Forward.diffuseReference([1,1,1],[1,1,1],1),[0,0,0]);});
  check('ambient channel once, own receiver, malformed energy',()=>{assert.deepEqual(Forward.diffuseReference([.08,.02,Infinity],[.5,1,1],.5,{advancedLighting:true}),[.02,.01,0]);assert.deepEqual(Forward.diffuseReference([.08,.08,.08],[0,0,0],1,{advancedLighting:true}),[0,0,0]);assert.deepEqual(Forward.diffuseReference([.08,.08,.08],[1,1,1],1,{advancedLighting:true},2),[0,0,0]);});
  check('shared ownership/native Y, explicit lane and bias',()=>{assert(Forward.HELPER_WGSL.includes(Ownership.PSEUDO_DEPTH_WGSL));for(const y of [0,6.5,359.5,1079.5])for(const category of ['ground','dynamic','foreground']){const s={worldZ:18,category,bias:.25},d=PseudoDepth.projectFragment({fragmentScreenY:y,localHeight:18/64,category,bias:.25}).depth01;assert(Forward.surfaceVisible(y,d,s));assert(!Forward.surfaceVisible(y,d-.001,s));}assert.throws(()=>Forward.normalizeSurface({worldZ:0,bias:512}),/half a lane/);assert.throws(()=>Forward.normalizeSurface({worldZ:0,layer:NaN}),/finite/);});
  check('SM601 support rejection and empty ownership',()=>{const p={object:7,depth:.5,normal:[.5,.5,1]};assert.equal(Forward.supportReason(p,p),0);assert.equal(Forward.supportReason(p,{...p,object:8}),2);assert.equal(Forward.supportReason(p,{...p,object:0}),2);assert.equal(Forward.supportReason(p,{...p,depth:.53}),1);assert.equal(Forward.supportReason(p,{...p,normal:[1,.5,.5]}),3);});
  check('large foliage only, grass/medium unchanged',()=>{const v={ambientVisibility:.5,directVisibility:1,incident:[.08,.02,0]},settings={ambient:.1,lighting:true,advancedLighting:true},base={x:6,rootY:6,h:12,w:4};for(const category of ['SHORT_GRASS','GROUND_MOSS','FERN']){const p={...base,category};assert.deepEqual(Foliage.shadeFoliageReference(p,[],v,settings).color,Foliage.shadeFoliageReference(p,[],v,{...settings,advancedLighting:false}).color);}const p={...base,category:'BUSH'},lit=Foliage.shadeFoliageReference(p,[],v,settings),off=Foliage.shadeFoliageReference(p,[],v,{...settings,advancedLighting:false});assert.equal(lit.indirect[0],.08*Foliage.PALETTE.BUSH[0]*.5);assert(lit.color[0]>off.color[0]);const blocked=Foliage.shadeFoliageReference(p,[],{...v,opaqueDepth:0},settings);assert.deepEqual(blocked.indirect,[0,0,0]);});
  check('water behind actor rejects, indirect separated',()=>{const sample={mask:1,currentDepth:.1,refractedDepth:.1,under:[.1,.1,.1],incident:[.08,0,0],ambientVisibility:.5};assert.deepEqual(Water.shadeWaterReference(sample,[],WATER_SETTINGS,[6,6]),[0,0,0,0]);const visible={...sample,currentDepth:1,refractedDepth:1},on=Water.shadeWaterReference(visible,[],WATER_SETTINGS,[6,6]),off=Water.shadeWaterReference(visible,[],{...WATER_SETTINGS,advancedLighting:false},[6,6]);assert(Math.abs(on[0]-off[0]-.08*Water.DEFAULTS.baseColor[0]*.5)<1e-10);assert.equal(on[1],off[1]);assert.equal(on[3],off[3]);});
  check('foliage ABI retained and light work capped',()=>{assert.equal(Foliage.INSTANCE_STRIDE,80);assert.equal(Foliage.OUTPUT_STRIDE,48);const p=Foliage.packInstances([{x:6,rootY:6,w:4,h:12,category:'BUSH',flags:.9,depthLayer:-1}]);assert.equal(p.byteLength,80);assert.equal(new Float32Array(p.buffer)[19],-1);assert(Math.abs(new Float32Array(p.buffer)[9]-.9)<1e-6);const params=Foliage.packParams(20,16,0,{},1,900);assert.equal(new Uint32Array(params.buffer)[3],17);});
  check('borrowed incident alternates without generation change',()=>{const{device}=mockDevice(),c=canonical(device),old=c.source;c.ssgi.current=c.b;c.ssgi.updateCount++;assert.throws(()=>Forward.assertFresh(old),/changed|stale/);const fresh=Forward.refreshSource(old,{device});assert.equal(fresh.incidentView,c.b);assert.equal(fresh._fresh.ssgi.generation,old._fresh.ssgi.generation);assert(Forward.assertFresh(fresh));});
  check('stale/mismatched upstream and quarter extents reject',()=>{const{device}=mockDevice(),c=canonical(device);c.visibility.valid=false;assert.throws(()=>Forward.refreshSource(c.source,{device}),/stale|invalid/);c.visibility.valid=true;c.ssgi.width++;assert.throws(()=>Forward.refreshSource(c.source,{device}),/extent/);c.ssgi.width--;assert.throws(()=>Forward.refreshSource(c.source,{device:{}}),/device/);c.ssgi.bindings=()=>({indirectQuarter:c.a,quarterWidth:1,quarterHeight:1});assert.throws(()=>Forward.refreshSource(c.source,{device}),/quarter/);});
  check('actual ownership close cannot retain cached destroyed views',()=>{const{device}=mockDevice(),c=actualCanonical(device);c.paths.gbuffer.close();assert.equal(c.paths.gbuffer.closed,undefined);assert.throws(()=>Forward.assertFresh(c.source),/changed|stale/);assert.throws(()=>Forward.refreshSource(c.source,{device}),/closed/);c.close();});
  check('actual lighting close invalidates already captured light resources',()=>{const{device}=mockDevice(),c=actualCanonical(device);c.paths.lighting.close();assert.equal(c.paths.lighting.closed,undefined);assert.throws(()=>Forward.assertFresh(c.source),/changed|stale/);assert.throws(()=>Forward.refreshSource(c.source,{device}),/closed/);c.close();});
  check('actual ownership resize round-trip is a distinct resource lifetime',()=>{const{device}=mockDevice(),c=actualCanonical(device),g=c.paths.gbuffer,gen=g.registry.generation;g.resize(40,32);g.resize(20,16);assert.equal(g.registry.generation,gen);assert.throws(()=>Forward.assertFresh(c.source),/changed|stale/);assert.throws(()=>Forward.refreshSource(c.source,{device}),/raw opaque resolved view/);const fresh=Forward.sourceFromPaths(c.paths);assert.notEqual(fresh.depthView,c.source.depthView);assert(Forward.assertFresh(fresh));c.close();});
  check('actual SSGI reset cannot reuse old raw composed view',()=>{const{device}=mockDevice(),c=actualCanonical(device);c.paths.ssgi.resetDevice(device);c.paths.ssgi.valid=true;assert.throws(()=>Forward.refreshSource(c.source,{device}),/raw opaque resolved view/);const paths={...c.paths,opaqueResolvedView:c.paths.ssgi.bindings().composed},fresh=Forward.sourceFromPaths(paths);assert.notEqual(fresh.sceneView,c.source.sceneView);assert(Forward.assertFresh(fresh));c.close();});
  check('actual canonical record replacement and destruction are detected',()=>{const{device}=mockDevice(),c=actualCanonical(device),r=c.paths.gbuffer.registry,old=r.require('sm200:depth').handle;r.require('sm200:depth').handle=device.createTexture({size:[20,16],format:'depth32float'});assert.throws(()=>Forward.assertFresh(c.source),/resource changed/);r.require('sm200:depth').handle=old;old.destroy();assert.throws(()=>Forward.assertFresh(c.source),/destroyed/);assert.throws(()=>Forward.refreshSource(c.source,{device}),/destroyed/);c.close();});
  check('actual SSGI known in-flight update cannot be borrowed',()=>{const{device}=mockDevice(),c=actualCanonical(device);c.paths.ssgi._updating=true;assert.throws(()=>Forward.assertFresh(c.source),/changed|stale/);assert.throws(()=>Forward.refreshSource(c.source,{device}),/in flight/);c.paths.ssgi._updating=false;assert(Forward.assertFresh(c.source));c.close();});
  check('neutral advanced resources persistent, cached groups bounded',()=>{const{device,state}=mockDevice(),c=canonical(device);c.paths.ssgi=null;const source=Forward.sourceFromPaths(c.paths),owner=new Forward.BindingOwner(device),layout={device};for(let i=0;i<20;i++)owner.bind(layout,source,{advancedLighting:true});assert.equal(state.groups.length,1);assert.equal(owner.diagnostics().estimatedBytes,56);assert.equal(owner.diagnostics().textureCount,1);assert.equal(owner.diagnostics().bufferCount,1);owner.close();assert.throws(()=>owner.bind(layout,source),/closed/);});
  {
    const{device,state}=mockDevice(),c=canonical(device),w=water(device);await w.initialize({advanced:true});const before=[state.textures.length,state.buffers.length],writes={querySet:{},beginningOfPassWriteIndex:0,endOfPassWriteIndex:1};for(let i=0;i<20;i++){c.ssgi.current=i%2?c.b:c.a;c.ssgi.updateCount++;const enc=device.createCommandEncoder();w.encode(enc,c.source,{roomId:'room'},WATER_SETTINGS,{timestampWrites:writes});device.queue.submit([enc.finish()]);}assert.deepEqual([state.textures.length,state.buffers.length],before);assert.equal(state.groups.length,3);assert.equal(state.commands.at(-1).passes[0].descriptor.timestampWrites,writes);assert.equal(w.diagnostics().forwardResources.estimatedBytes,56);checks.push('water persistent resources, two history bindings, pass timestamp forwarding');w.close();
  }
  {
    const{device,state}=mockDevice(),c=canonical(device),p=new Foliage.WebGPUFoliagePass(device,{width:20,height:16});p.upload([{x:6,rootY:6,w:4,h:12,category:'BUSH'}]);p.initialize({advanced:true});const before=[state.textures.length,state.buffers.length],writes={querySet:{},beginningOfPassWriteIndex:0,endOfPassWriteIndex:1};for(let i=0;i<20;i++){c.ssgi.current=i%2?c.b:c.a;c.ssgi.updateCount++;const enc=device.createCommandEncoder();p.encode(enc,c.source,{advancedLighting:true},0,'indirect',{timestampWrites:writes});device.queue.submit([enc.finish()]);}assert.deepEqual([state.textures.length,state.buffers.length],before);assert.equal(state.groups.length,3);assert.equal(state.commands.at(-1).passes[0].descriptor.timestampWrites,writes);assert.equal(p.diagnostics().instanceBytes,208*80);assert.equal(p.diagnostics().outputBytes,208*48);checks.push('foliage persistent buffers, bounded groups and timestamp forwarding');p.close();
  }
  {
    const{device,state}=mockDevice(),c=canonical(device),w=water(device),scope={submits:0,submit(commands){this.submits++;device.queue.submit(commands);}};await w.render(c.source,{roomId:'room'},WATER_SETTINGS,{performanceTimingScope:scope,wait:false});assert.equal(scope.submits,1);assert.equal(state.waits,0);state.failSubmit=true;await assert.rejects(w.render(c.source,{roomId:'room'},WATER_SETTINGS,{wait:false}),/submit failure/);assert.equal(w.valid,false);assert.throws(()=>w.outputTexture(),/invalid/);checks.push('water explicit SM500 submission excludes blocking waits and failure invalidates output');w.close();
  }
  {
    const{device,state}=mockDevice(),w=water(device),gate=deferred();state.compileGate=gate;const a=w.initialize({advanced:true}),b=w.initialize({advanced:true});await until(()=>state.compileCalls===1);gate.resolve();await Promise.all([a,b]);assert.equal(state.pipelines.length,2);assert.equal(state.buffers.length,3);assert.equal(state.textures.length,3);checks.push('overlapping initialization shares persistent pipelines and forward resources');w.close();
  }
  {
    const{device,state}=mockDevice(),c=canonical(device),w=water(device),gate=deferred();state.compileGate=gate;const run=w.render(c.source,{roomId:'room'},WATER_SETTINGS,{wait:false});await until(()=>state.compileCalls===1);c.ssgi.updateCount++;gate.resolve();await assert.rejects(run,/changed|stale/);assert.equal(state.submits.length,0);checks.push('producer changes during pipeline preparation reject before submission');w.close();
  }
  {
    const{device,state}=mockDevice(),c=canonical(device),w=water(device);await w.initialize({advanced:true});state.completion=deferred();const run=w.render(c.source,{roomId:'room'},WATER_SETTINGS);await until(()=>state.waits===1);c.visibility.invalidate=true;c.visibility.valid=false;state.completion.resolve();await assert.rejects(run,/changed|stale/);assert.equal(w.valid,false);checks.push('post-submission source invalidation cannot publish valid water output');w.close();
  }
  {
    const{device,state}=mockDevice(),c=canonical(device),w=water(device),gate=deferred();state.compileGate=gate;const run=w.render(c.source,{roomId:'room'},WATER_SETTINGS,{wait:false});await until(()=>state.compileCalls===1);await assert.rejects(w.render(c.source,{roomId:'room'},WATER_SETTINGS),/concurrent/);w.close();gate.resolve();await assert.rejects(run,/lifecycle/);assert.equal(state.submits.length,0);checks.push('concurrent water update and close during compile reject without submission');
  }
  {
    const a=mockDevice(),b=mockDevice(),c=canonical(a.device),w=water(a.device),gate=deferred();a.state.compileGate=gate;const pending=w.initialize({advanced:true});await until(()=>a.state.compileCalls===1);w.resetDevice(b.device);gate.resolve();await assert.rejects(pending,/lifecycle/);await w.initialize({advanced:true});assert.equal(w.pipeline.device,b.device);assert.equal(w.advancedPipeline.device,b.device);a.loss.resolve();await Promise.resolve();assert.equal(w.deviceLost,false);b.loss.resolve();await Promise.resolve();assert.equal(w.deviceLost,true);assert.throws(()=>w.outputTexture(),/invalid/);checks.push('device replacement isolates pending pipelines and generation-scoped loss');w.close();
  }
  {
    const{device,state}=mockDevice(),c=canonical(device),p=new Foliage.WebGPUFoliagePass(device,{width:20,height:16});p.upload([{x:6,rootY:6,w:4,h:12,category:'BUSH'}]);state.completion=deferred();const run=p.render(c.source,{advancedLighting:true});await until(()=>state.waits===1);p.invalidate();state.completion.resolve();await assert.rejects(run,/lifecycle/);assert.equal(p.valid,false);checks.push('explicit foliage invalidation during queue wait remains invalid');p.close();
  }
  console.log(JSON.stringify({schema:'steelmoth-sm702-forward-cpu-api/v1',ok:true,checks:checks.length,names:checks,evidenceBoundary:'Deterministic math and mocked API/lifetime checks only; no GPU execution, timing or visual claim.'}));
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
