'use strict';
// Deterministic fixture/consumer contracts. These are not GPU or visual evidence.
const assert=require('assert'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const F=require('./sm702_forward_fixtures.js'),D=require('../engine/pseudo_depth.js'),O=require('../engine/webgpu_ownership.js'),Order=require('../engine/webgpu_ordering.js'),Forward=require('../engine/webgpu_forward_lighting.js'),Water=require('../engine/webgpu_water.js'),Leaf=require('../engine/webgpu_foliage.js'),Glass=require('../engine/webgpu_transparent_fx.js'),BW=require('./experiments/sm702_water_baseline.js'),BL=require('./experiments/sm702_foliage_baseline.js'),BT=require('./experiments/sm702_transparent_fx_baseline.js');
let count=0;function check(value,label){assert(value,label);count++;}
for(const [name,b]of Object.entries(F.BASELINES)){const bytes=fs.readFileSync(path.resolve(__dirname,'..',b.path),'utf8').replace(/\r\n/g,'\n');check(crypto.createHash('sha256').update(bytes).digest('hex')===b.sha256,name+' exact frozen LF pin');}
for(const kind of ['representative','stress']){
  const scene=F.sceneDescription(1920,1080,kind),expected=kind==='stress'?{ripples:12,foliage:208,transparent:640,lights:17}:{ripples:2,foliage:6,transparent:5,lights:2};
  for(const [key,n]of Object.entries(expected))check(scene[key].length===n,kind+' '+key+' bounded exact count');
  const meta={source_size:[1,1],regions:{white:[0,0,1,1]}},input={frame:scene.frame,sprites:scene.transparent,overlays:scene.overlays},a=BT.buildCompatibilityFrame(input,meta),b=Glass.buildCompatibilityFrame(input,meta);
  check(a.stats.dropped===0&&b.stats.dropped===0&&b.stats.unresolvedCount===0,kind+' exact resolved transparent ownership/cap');
  for(const stage of ['world-alpha','world-additive','top-alpha'])check(F.maxDiff(BT.flattenStage(a,stage),Glass.flattenStage(b,stage))===0,kind+' '+stage+' preserves legacy vertices');
  check(b.stages['world-alpha'].some(q=>q.forwardMaterial.material==='clear-glass'&&q.forwardMaterial.diffuseWeight===0),kind+' explicit clear zero GI');
  check(b.stages['world-alpha'].some(q=>q.forwardMaterial.material==='frosted-glass'&&q.forwardMaterial.diffuseWeight===.6),kind+' explicit frosted bounded GI');
  const plan=Order.buildFramePlan({raw:true,water:true,foliage:{instances:scene.foliage},transparentFrame:b});check(Order.validatePlan(plan)&&plan.order.join()===Order.canonicalStageOrder().join(),kind+' actual consumer plan follows canonical order');
  check(plan.stages.find(q=>q.id==='post').operation==='raw-copy',kind+' explicit raw post copy boundary');
  const instances=Leaf.packInstances(scene.foliage),f=new Float32Array(instances.buffer,instances.byteOffset,instances.byteLength/4),u=new Uint32Array(instances.buffer,instances.byteOffset,instances.byteLength/4);
  check(scene.foliage.every((q,i)=>Math.abs(f[i*20+9]-q.frontBlend)<1e-7),kind+' preserved actual front classifier scalar');
  check(scene.foliage.some((q,i)=>(u[i*20+16]&Leaf.CLASS_FLAGS.macro)!==0)&&scene.foliage.some((q,i)=>(u[i*20+16]&Leaf.CLASS_FLAGS.tiny)!==0),kind+' real macro and exempt production classes');
}
const scene=F.sceneDescription(),moving=F.sceneDescription(67,51,'representative',{actorX:26,angle:225}),deleted=F.sceneDescription(67,51,'representative',{deletedColumns:4}),reveal=F.sceneDescription(67,51,'representative',{revealed:true});
const Lighting=require('../engine/webgpu_lighting.js'),dimWarm=F.sceneDescription(67,51,'representative',{angle:90,actorX:22,intensity:.04,lightColour:[1,.95,.85]}),dimBlue=F.sceneDescription(67,51,'representative',{angle:90,actorX:22,intensity:.04,lightColour:[.15,.4,1]}),warmCanonical=Lighting.buildCanonicalLights(dimWarm,F.SETTINGS.lighting),blueCanonical=Lighting.buildCanonicalLights(dimBlue,F.SETTINGS.lighting),warmDirect=Glass.glassDirectReference(warmCanonical,[30.5,16.5],8),blueDirect=Glass.glassDirectReference(blueCanonical,[30.5,16.5],8);
check(warmDirect.every(v=>v>0&&v<.21)&&blueDirect.every(v=>v>0&&v<.21),'labelled dim controls actually produce unsaturated canonical direct reference');check(F.maxDiff(warmDirect,blueDirect)>.001,'labelled canonical RGB controls change the actual light reference');check(scene.lights[0].intensity===2.4&&scene.lights[0].color.join()==='1,0.95,0.85','ordinary benchmark light settings preserved by optional controls');
check(scene.sprites[2].id===moving.sprites[2].id&&scene.sprites[2].transform.x!==moving.sprites[2].transform.x,'moving actual actor changes coverage with stable identity');
check(scene.lights[0].id===moving.lights[0].id&&scene.lights[0].x!==moving.lights[0].x,'moving actual canonical light stable identity');
check(scene.sprites[1].id===deleted.sprites[1].id&&deleted.sprites[1].transform.w===12,'partial donor deletion changes geometry not all IDs');
check(reveal.sprites[2].spriteId==='blocker'&&reveal.sprites[2].id===scene.sprites[2].id,'reveal changes real material under stable actor identity');
const atlas=F.atlasData(),instances=O.buildOwnershipSceneInstances(scene,atlas.meta);check(instances.length===3&&instances.every(q=>q.objectId>0),'generated atlas uses actual production ownership packing');
check(atlas.albedo.length===atlas.width*atlas.height*4&&atlas.nr.length===atlas.hm.length,'generated Material-v2 inputs coordinate-identical');
for(const [height,worldZ]of [[0,0],[128/255,64*128/255],[191/255,64*191/255]]){const d=D.projectFragment({fragmentScreenY:17.5,localHeight:height,category:'dynamic',layer:0}).depth01;check(Forward.surfaceVisible(17.5,d,{worldZ,category:'dynamic',layer:0,bias:0}),'canonical own surface equal depth accepted');check(!Forward.surfaceVisible(17.5,d-.005,{worldZ,category:'dynamic',layer:0,bias:0}),'canonical nearer owner rejects surface');}
const n={depth:.5,object:7,normal:[.5,.5,1]};check(Forward.supportReason(n,n)===0,'same canonical surface GI support');check(Forward.supportReason(n,{...n,object:8})===2,'foreign quarter owner rejects GI');check(Forward.supportReason(n,{...n,depth:.6})===1,'quarter depth discontinuity rejects GI');check(Forward.supportReason(n,{...n,normal:[1,.5,.5]})===3,'quarter normal discontinuity rejects GI');
const incident=[.03,.04,.05],own=[.2,.4,.7],options={advancedLighting:true,indirectWeight:.6};for(const b of [0,.2,.6,1]){const out=Forward.diffuseReference(incident,own,b,options);check(out.every((x,i)=>Math.abs(x-incident[i]*own[i]*b*.6)<1e-12),'ambient B '+b+' exactly once reference');}
check(Forward.diffuseReference([10000,-1,Infinity],[1,1,1],1,options).every(x=>Number.isFinite(x)&&x>=0&&x<=.048),'HDR/invalid forward incident bounded reference');
check(Forward.diffuseReference(incident,own,.5,{advancedLighting:false}).every(x=>x===0),'explicit off neutral GI');check(Forward.diffuseReference(incident,own,.5,options,2).every(x=>x===0),'rejected quarter support neutral GI');
const macro=scene.foliage.find(q=>Leaf.classificationFor(q).macroEligible),tiny=scene.foliage.find(q=>Leaf.classificationFor(q).role==='receiver-only');
const visibility={incident,ambientVisibility:.6,directVisibility:.5},lights=[{position:[macro.x+20,macro.rootY-15,40],radius:200,intensity:1,color:[1,.8,.6]}],base=Leaf.shadeFoliageReference(macro,lights,visibility,{...F.SETTINGS.foliage,advancedLighting:false},.4),on=Leaf.shadeFoliageReference(macro,lights,visibility,{...F.SETTINGS.foliage,advancedLighting:true},.4);
check(on.indirect.some(x=>x>0)&&on.color.every((x,i)=>Math.abs(x-base.color[i]-on.indirect[i])<1e-12),'large foliage adds own diffuse without changing legacy illumination');check(Leaf.shadeFoliageReference(tiny,lights,visibility,{advancedLighting:true},.4).indirect.every(x=>x===0),'tiny class exempt reference');
check(F.FOLIAGE_COMPOSE_WGSL.includes(O.PSEUDO_DEPTH_WGSL)&&F.FOLIAGE_COMPOSE_WGSL.includes('smOwnershipDepth(in.p.y,in.surface.x,in.surface.y,in.surface.z)'),'fixture compositor uses shared canonical native fragment depth');
check(F.FOLIAGE_COMPOSE_WGSL.includes('var<storage,read>shaded')&&F.FOLIAGE_COMPOSE_WGSL.includes('out.colour=o.color'),'composition consumes actual production output storage');
const sourceDescriptors=[],submits=[],nativeQueue={submit:buffers=>submits.push(buffers),writeBuffer(){}},nativeEncoder={beginRenderPass:desc=>{sourceDescriptors.push(desc);return{end(){}};},finish:()=>({actual:'water-command'})},native={queue:nativeQueue,createCommandEncoder:()=>nativeEncoder};
const cap=F.captureLegacyWaterDevice(native),writes={querySet:{},beginningOfPassWriteIndex:0,endOfPassWriteIndex:1};cap.begin(writes);cap.device.createCommandEncoder().beginRenderPass({label:'actual water',colorAttachments:[]}).end();cap.queue.submit([cap.device.createCommandEncoder().finish()]);const buffers=cap.finish();check(submits.length===0&&buffers.length===1&&buffers[0].actual==='water-command','frozen water actual command captured without hidden submission');check(sourceDescriptors[0].timestampWrites===writes&&sourceDescriptors[0].label==='actual water','frozen actual render pass receives observer only');nativeQueue.submit([...buffers,{actual:'all caller forward'}]);check(submits[0].length===2,'complete actual buffers can be one atomic submission');
let actualCompute=null;const encoder={beginComputePass:d=>{actualCompute=d;return{};},finish:()=>1};F.timestampEncoder(encoder,'beginComputePass',writes).beginComputePass({label:'frozen foliage'});check(actualCompute.timestampWrites===writes&&actualCompute.label==='frozen foliage','frozen foliage real compute pass observed without replacing kernel');
const large=new Float32Array(1920*1080);large[123]=.1;large[999999]=.9;check(F.extrema(large).min===0&&Math.abs(F.extrema(large).max-.9)<1e-6,'full-HD extrema bounded scalar scan');
check(F.mean([1,2,3])===2&&F.percentile([3,1,2],.95)===3,'timing statistics retain samples');
console.log(JSON.stringify({schema:'steelmoth-sm702-forward-fixture-validation/v1',ok:true,assertions:count,boundary:'CPU fixture/reference and instrumentation contracts only; no GPU, visual, hardware or performance claim.'}));
