'use strict';
const assert=require('assert');
const O=require('../engine/webgpu_occluders.js');
const C=require('../engine/webgpu_clusters.js');
const D=require('../engine/webgpu_dominance.js');
const H=require('../engine/webgpu_dso.js');
const opts={tileSize:32,maxOccluders:64,maxPerTile:16,maxTileRefs:512};
const angles=[0,45,90,135,180,225,270,315];
const polar=(center,deg,r=120,id='player-light')=>{const a=deg*Math.PI/180;return{id,position:[center[0]+Math.cos(a)*r,center[1]+Math.sin(a)*r,24],radius:500,intensity:1}};
const centerOf=b=>[(b[0]+b[2])*.5,(b[1]+b[3])*.5];
function fixture(roomId,occluders){const scene={frame:{roomId,logicalSize:[128,96]},occluders};const occ=O.buildOccluderSnapshot(scene,opts),clusters=C.buildClusterSnapshot(occ);return{scene,occ,clusters}}
function planFor(f,light){const dom=D.buildDominanceSnapshot(f.clusters,f.occ,[light]);assert(dom.records.length>0,'fixture must produce at least one dominance record');const plan=H.buildDSOPlan(f.clusters,f.occ,dom,{lightId:light.id});return{dom,plan,mask:H.rasterizeDSOReference(plan)}}
const box=fixture('sm303-box',[{id:'box',rect:[46,30,82,68],root:{x:64,y:68},kind:'machine',majorOccluder:true,sections:[{z:24}]}]);assert.strictEqual(box.clusters.clusters.length,1);
for(const deg of angles){const light=polar(centerOf(box.clusters.clusters[0].bounds),deg),a=planFor(box,light),b=planFor(box,light);assert.strictEqual(a.plan.diagnostics.fullStrengthWedgeCount,1,`box ${deg}: exactly one primary hard wedge`);assert.strictEqual(a.plan.diagnostics.secondaryFullStrengthWedgeCount,0,`box ${deg}: no secondary full wedge`);assert.strictEqual(a.plan.signature,b.plan.signature,`box ${deg}: fixed plan deterministic`);assert.deepStrictEqual(Array.from(a.mask),Array.from(b.mask),`box ${deg}: fixed hard mask deterministic`);const m=H.connectedMetrics(a.mask,128,96);assert(m.totalArea>200,`box ${deg}: visible hard macro shadow survives`);assert.strictEqual(m.disconnectedIslandCount,1,`box ${deg}: single box remains one coherent hard silhouette`)}
const bins=fixture('sm303-bins',[{id:'bin:left',rect:[20,20,48,60],root:{x:34,y:60},kind:'machine',source:'bin',sections:[{z:22}]},{id:'bin:middle',rect:[46,30,74,70],root:{x:60,y:70},kind:'machine',source:'bin',sections:[{z:24}]},{id:'bin:right',rect:[72,5,100,45],root:{x:86,y:46},kind:'machine',source:'bin',sections:[{z:20}]}]);assert.strictEqual(bins.clusters.clusters.length,1,'three-bin structural fixture must form one SM-301 cluster');const binCenter=centerOf(bins.clusters.clusters[0].bounds);
for(const deg of angles){const light=polar(binCenter,deg),{plan,mask}=planFor(bins,light),m=H.connectedMetrics(mask,128,96);assert.strictEqual(plan.jobs.length,1,`bins ${deg}: one cluster/light DSO job`);assert.strictEqual(plan.diagnostics.fullStrengthWedgeCount,1,`bins ${deg}: dominant owner is the sole long macro wedge`);assert.strictEqual(plan.diagnostics.secondaryFullStrengthWedgeCount,0,`bins ${deg}: non-owners never become equal long wedges`);assert(plan.members.every(s=>s.throwLength<=plan.jobs[0].ownerThrow*H.DEFAULTS.secondaryThrowFraction+1e-6),`bins ${deg}: secondary structure stays within bounded throw`);assert(m.totalArea>0,`bins ${deg}: DSO produces a mask`);assert(plan.tileRefs.length<=H.DEFAULTS.maxTileRefs,`bins ${deg}: tile-local reference list bounded`)}
const upLight=polar(binCenter,270,120,'player-light'),up=planFor(bins,upLight),upMetrics=H.connectedMetrics(up.mask,128,96),baseline=H.rasterizeIndependentBaseline(up.plan,bins.occ,{clusterSnapshot:bins.clusters,lightPosition:upLight.position}),baselineMetrics=H.connectedMetrics(baseline,128,96);assert(baselineMetrics.disconnectedIslandCount>upMetrics.disconnectedIslandCount,'cluster-level DSO must reduce disconnected competing macro islands versus independent per-object wedges');assert(baselineMetrics.totalSmallIslandArea>upMetrics.totalSmallIslandArea,'cluster-level DSO must reduce minor disconnected island area');assert(baselineMetrics.silhouetteEdgeLength>upMetrics.silhouetteEdgeLength,'cluster-level DSO must reduce fractured macro-shadow edge length');assert.strictEqual(up.plan.diagnostics.distanceSimplification,false);assert.strictEqual(up.plan.diagnostics.darkBloom,false);assert.strictEqual(up.plan.diagnostics.temporalAccumulation,false);
const packed=H.packJobs(up.plan.jobs),dv=new DataView(packed.buffer,packed.byteOffset,packed.byteLength);assert.strictEqual(H.JOB_STRIDE,64);assert.strictEqual(H.MEMBER_STRIDE,32);assert.strictEqual(dv.getUint32(0,true),up.plan.jobs[0].clusterId);assert.strictEqual(dv.getUint32(4,true),up.plan.jobs[0].ownerObjectId);assert.strictEqual(dv.getUint32(16,true),up.plan.jobs[0].memberCount);
const sweepOwners=[];let history=new Map();for(const deg of [-2,-1,0,1,2]){const light=polar(binCenter,deg,600,'player-sweep'),dom=D.buildDominanceSnapshot(bins.clusters,bins.occ,[light],history),record=dom.records[0];sweepOwners.push(record.ownerObjectId);history=dom.history;const p=H.buildDSOPlan(bins.clusters,bins.occ,dom,{lightId:light.id}),first=H.rasterizeDSOReference(p),second=H.rasterizeDSOReference(p);assert.deepStrictEqual(Array.from(first),Array.from(second),`moving-light ${deg}: each fixed state is deterministic`)}assert.strictEqual(new Set(sweepOwners).size,1,'SM-302 hysteresis keeps DSO owner stable through ±1–2 degree sweep');
console.log('SM-303 DSO hard-core deterministic + structural tests: PASS',JSON.stringify({boxAngles:8,binAngles:8,upMetrics,baselineMetrics}));
