#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def text(rel): return (ROOT/rel).read_text(encoding='utf-8')
def need(hay,needle,label):
    if needle not in hay: raise SystemExit(f'SM-304 contract FAIL: {label}: missing {needle!r}')
engine=text('engine/webgpu_dso_hierarchy.js');doc=text('docs/WEBGPU_DSO_HIERARCHY_SM304.md');webapp=text('webapp.js');sw=text('sw.js');workflow=text('.github/workflows/sm304-dso-hierarchy.yml')
need(engine,"SNAPSHOT_SCHEMA='steelmoth-webgpu-dso-hierarchy-snapshot/v1'",'snapshot schema')
need(engine,"quality:'Medium'",'bounded default quality')
need(engine,"tileSize:16",'compact DSO traversal tile')
need(engine,'sourceDistance','projected-throw selection')
need(engine,'levelForDistance','near/mid/far selection')
need(engine,'distanceSimplification:true','hierarchy semantics')
need(engine,'projectedThrowSelection:true','diagnosed projected-throw selection')
need(engine,'expensiveTileSkipRatio','tile-culling diagnostics')
need(engine,'lastStaleClearTileCount','stale tile clearing diagnostics')
need(engine,'texture_storage_2d<r32float,write>','real WebGPU hard-mask output')
need(engine,'darkBloom:false','SM-305 remains deferred')
need(engine,'temporalAccumulation:false','SM-306 remains deferred')
need(doc,'exact SM-303 owner bounds','documented near-detail contract')
need(doc,'previously active tile that becomes inactive','documented stale clearing')
need(doc,'does not claim GTX 1650 Super GPU timing','truthful timing evidence boundary')
need(doc,'SM-305 Dark Bloom','Dark Bloom scope boundary');need(doc,'SM-306 temporal','temporal scope boundary');need(doc,'SM-307 final visibility','composition scope boundary')
need(webapp,'./engine/webgpu_dso_hierarchy.js?v=sm304-1','runtime staging')
need(sw,'./engine/webgpu_dso_hierarchy.js?v=sm304-1','offline cache staging')
need(sw,"small-machine-web-v1.2.3-r15",'cache revision bump')
need(workflow,'validate_webgpu_dso_hierarchy_browser.py --require-webgpu','required real-WebGPU gate')
need(workflow,'webgpu-dso-hierarchy-smoke.html','browser fixture workflow scope')
print('SM-304 DSO hierarchy source/document/runtime contract: PASS')
