'use strict';
// CPU-only oracle/mutation/source-preservation evidence. No GPU execution.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/\r\n/g,'\n'),sha=s=>crypto.createHash('sha256').update(s).digest('hex'),blob=s=>crypto.createHash('sha1').update(`blob ${Buffer.byteLength(s)}\0`).update(s).digest('hex');
const Policy=require('./sm601_neutral_probe_policy.js'),S=require('./sm601_gtao_arithmetic_study.js'),manifest=JSON.parse(read('tools/sm601_arithmetic_canonical_probe_manifest.json')),page=read('sm601-gtao-arithmetic-study.html'),engine=read('engine/webgpu_gtao.js'),context={SteelMothWebGPUResources:{},module:{exports:{}}};vm.runInNewContext(engine,context);const G=context.module.exports;
function section(start,end){const a=page.indexOf(start),b=page.indexOf(end,a);assert(a>=0&&b>a,start);return page.slice(a,b)}
const preserved=manifest.preserved;
assert.equal(blob(engine),preserved.engineGitBlob);assert.equal(blob(read('tools/sm601_gtao_arithmetic_study.js')),preserved.arithmeticGeneratorGitBlob);assert.equal(sha(G.RAW_WGSL),preserved.rawWGSL);assert.equal(sha(G.UPSAMPLE_WGSL),preserved.reconstructionWGSL);assert.equal(sha(G.parameterBytes.toString()),preserved.parameterBytesFunctionSha256);
assert.equal(sha(section('    function dispatch(','    async function capture(')),preserved.dispatchFunctionSha256);assert.equal(sha(section('    if(benchmark){','    await device.queue.onSubmittedWorkDone();')),preserved.benchmarkLoopSha256);assert.equal(sha(section('  function equalBytes(','  function field(')),preserved.exactEqualityFunctionSha256);
assert.equal(sha(section('          for(let variant=1;variant<captures.length;', '          report.exactOutputEqualityPassed=true;')),preserved.exactCandidateEqualityLoopSha256);assert.equal(sha(section("          if(c.pattern==='weak-weight'){",'        }\n        const err=await device.popErrorScope();')),preserved.fallbackWitnessBlockSha256);
assert.equal(Policy.ORDINARY_PLANE_ABSOLUTE_BOUND,manifest.canonicalOrdinaryArithmeticBound);assert.equal(Policy.ORDINARY_PLANE_ABSOLUTE_BOUND,2e-6);
assert(page.indexOf('not byte-identical.')<page.indexOf('Neutral.evaluate('),'strict candidate A/B must precede baseline neutral policy');
assert(page.includes("check(vis[0]===.25&&dbg[0]===0,'WGSL fallback witness did not select nearestRaw.')"),'fallback pixel/confidence assertion must remain exact');assert(page.includes("check([raw,up,total].every(x=>Number.isFinite(x)&&x>0)"),'positive timestamp gate must remain exact');assert(page.includes("check(baselineField.min>=.149&&baselineField.max<=1"),'finite/bounded visibility gate must remain');
const raw=new Float32Array([1,.5,1,0]),owned=new Float32Array([.5,.5]),empty=new Float32Array([1,0]);
function valueBelowOne(steps){const word=new Uint32Array([0x3f800000-steps]);return new Float32Array(word.buffer)[0]}
function evaluate(value,options={}){return Policy.evaluate({pattern:'plane',enabled:true,raw,visibility:new Float32Array([value]),depth:owned,...options})}
assert(evaluate(1).ok);assert(evaluate(valueBelowOne(1)).ok,'retained one-ULP occupied-plane witness must follow current ordinary arithmetic policy');assert(evaluate(valueBelowOne(33)).ok,'last representable value within existing bound accepted');
for(const value of [valueBelowOne(34),1-4e-6,.999,1.0000001192092896,NaN,Infinity])assert.equal(evaluate(value).ok,false,`out-of-bound/nonfinite plane value ${value} must fail`);
for(const options of [{pattern:'empty'}, {enabled:false}, {depth:empty}]){assert(evaluate(1,options).ok);assert.equal(evaluate(valueBelowOne(1),options).ok,false,'literal-neutral one-ULP drift must fail')}
for(const options of [{}, {pattern:'empty'}, {enabled:false}]){const drift=raw.slice();drift[0]=valueBelowOne(1);assert.equal(evaluate(1,{...options,raw:drift}).ok,false,'raw neutral visibility must remain exactly1')}
const mixed=Policy.evaluate({pattern:'plane',enabled:true,raw,visibility:new Float32Array([valueBelowOne(1),1]),depth:new Float32Array([.5,.5,1,0])});assert(mixed.ok);assert.equal(mixed.occupiedPixels,1);assert.equal(mixed.literalPixels,1);assert.equal(Policy.evaluate({pattern:'plane',enabled:true,raw,visibility:new Float32Array([valueBelowOne(1),valueBelowOne(1)]),depth:new Float32Array([.5,.5,1,0])}).ok,false);
assert.equal(Policy.evaluate({pattern:'dense',enabled:true,raw,visibility:new Float32Array([.5]),depth:owned}).required,false,'ordinary dense AO is not relabeled neutral');
const byteContext={};vm.createContext(byteContext);vm.runInContext(section('  function equalBytes(','  function field('),byteContext);
for(let plane=0;plane<3;plane++){const a=new Uint8Array(32),b=a.slice();assert(byteContext.equalBytes(a,b));for(const index of [0,15,31]){b[index]^=1;assert.equal(byteContext.equalBytes(a,b),false,'any candidate bit difference must fail');b[index]^=1}assert.equal(byteContext.equalBytes(a,new Uint8Array(31)),false)}
const [ideal,witness]=[1,valueBelowOne(1)].map(x=>new Uint8Array(new Float32Array([x]).buffer));assert.equal(byteContext.equalBytes(ideal,witness),false,'ordinary baseline tolerance must never become candidate A/B tolerance');
(async()=>{for(const variant of S.VARIANTS){const candidate=await S.createShaders(G.RAW_WGSL,G.UPSAMPLE_WGSL,variant);assert.deepEqual({raw:candidate.rawSha256,reconstruction:candidate.upSha256},preserved.candidateShaders[variant])}
console.log(JSON.stringify({schema:'steelmoth-sm601-canonical-neutral-policy-cpu/v1',ok:true,gpuExecuted:false,frozenStudyHead:manifest.frozenStudyHead,preservedWitnessHead:manifest.preservedWitnessHead,ordinaryOccupiedPlaneAbsoluteBound:Policy.ORDINARY_PLANE_ABSOLUTE_BOUND,oneUlpWitness:valueBelowOne(1),lastAllowedF32:valueBelowOne(33),firstRejectedF32:valueBelowOne(34),checks:['complete frozen engine/generator source','all four shader pairs','parameter serialization source','dispatch/timing loop/equality source','occupied-plane boundary mutants','exact literal/raw neutral mutants','mixed occupied/unoccupied plane controls','strict candidate bit mutations','exact fallback and positive timestamp guards']}));})().catch(error=>{console.error(error?.stack||error);process.exitCode=1});
